import React from 'react';
import { Helmet } from 'react-helmet';

const Privacy = () => {
    return (
        <div className='max-w-7xl mx-auto p-10'>
            <Helmet>
                <title>Privacy policy</title>
            </Helmet>
            <div className="">
                <h2 className="text-3xl font-semibold mb-5">CoStay Privacy Statement</h2>
                <p className="mb-5">CoStay LLC owns and operates an online platform that provides users with information, recommendations and services related to travel and leisure, including tools for researching and/or booking hotels, rentals and other accommodations, attractions and experiences, restaurants, flights, and cruises, among other leisure-related services. In this Statement, we refer to these as our “Services”.</p>

                <p className="mb-5">The information that you and others entrust us with enhances our ability to provide more relevant, personalized  and helpful Services. We know that sharing your information with us is based on trust. We take your trust in us seriously and are committed to providing you helpful information, products and services, curated based on the information you have shared with us. Equally, and perhaps more importantly, we are committed to respecting your privacy when you visit our website or use our Services and being transparent about how we use the information you have entrusted to us.</p>

                <p className="mb-5">This Statement describes how we obtain, use, and process your information hopefully, in an easily understandable and transparent manner. It informs you of the rights you have, how you can exercise them and how you can contact us. Please review this Statement carefully to learn about our practices with respect to information and privacy. By visiting our websites and related mobile applications, as well as other online platforms such as our affiliated partners’ websites, apps and social media, whether on a computer, phone, tablet, or similar device (each of these is referred to as a “Device”), you acknowledge and confirm that you have read this Statement.</p>

                <p className="mb-5">We offer our Services to users in a number of countries and territories where the laws and customs differ. This Statement provides a general overview of our privacy practices. In addition, Sections 12 through 15 of this Statement provide specific information relevant to users residing in certain regions or countries.</p>

                <p className="mb-8">When you access or use our Services, we collect and process information from and about you to provide the Services in a more personalized  and relevant way. Some information we collect passively, for example, with our servers or with cookies or other similar tracking technologies. Some information we collect from different sources, including from you, affiliated entities, business partners, and other independent third-party sources. When you use our Services by “clicking-through” from a third-party website or when you visit third-party websites via our Services, those third-party websites may share information with us about your use of their service. Any information that we receive from third-party websites may be combined with the information provided by you.</p>
            </div>

            <div className="">
                <h2 className="text-3xl font-semibold mb-5">CoStay Terms Statement</h2>
                <p className="mb-5">Welcome to the CoStay websites and mobile properties located at www.costay.com and applicable country top level domains (including sub-domains associated with them), related software applications (sometimes referred to as “apps”), data, SMS, APIs, email, chat and telephone correspondence, buttons, widgets and ads (collectively, all of these items shall be referred to herein as the “Services”; more generally, the CoStay websites and mobile properties shall hereinafter be referred to herein as “websites”). The Services are offered to you conditioned upon your acceptance of the terms, conditions, and notices set forth below (collectively, this “Agreement”). By accessing or using the Services, you agree to be bound by this Agreement and represent that you have read and understood its terms. Please read this Agreement carefully, as it contains information concerning your legal rights and limitations on these rights, as well as a section regarding applicable law and jurisdiction of disputes. If you do not accept all of these terms and conditions, you are not authorized to use the Services. If you have a CoStay account and wish to terminate this Agreement, you can do so at any time by closing your account and no longer accessing or using the Services (a description of how to do so is available here).</p>
                <p className="mb-5">Any information, text, links, graphics, photos, audio, videos, data, code or other materials or arrangements of materials that you can view on, access or otherwise interact with through the Services shall be referred to as “Content”. The terms “we”, “us”, “our” and “CoStay” refer to CoStay LLC, a Delaware limited liability company located in the United States of America (“CoStay”). “Services” as defined above refers to those provided by CoStay or our corporate affiliates (CoStay and such entities, when one or more are referred to, shall be collectively defined as the “CoStay Companies”). For the avoidance of doubt, the websites are all owned and controlled by CoStay.  However, some specific Services made available via the websites may be owned and controlled by CoStay’s corporate affiliates, for example Services facilitating the booking of Vacation Rentals, Restaurant Reservations and Experiences with third-party suppliers (see below). As part of our Services, we may send you notifications about special offers, products, or additional services available from us, our affiliates, or our partners, that may be of interest to you. Such notifications will typically be sent through newsletters and marketing communications and represent efforts to get to know you and your preferences better across our Services and those of our affiliates. In turn, this enables customisation of the services in line with those preferences.</p>
                <p className="mb-5">The term “you” refers to the individual, company, business organization, or other legal entity using the Services and/or contributing Content to them. The Content that you contribute, submit, transmit and/or post to or through the Services shall be referred to variously as “your Content”, “Content of yours”, and/or “Content you submit.”</p>

                <p className="mb-5">The Services are provided solely to:</p>
                <p className="mb-5">Assist customers in gathering travel information, posting Content, and searching for and booking travel services and reservations; and Assist travel, tourism and hospitality businesses in engaging with customers and potential customers, by way of free and/or paid-for services offered by or through the CoStay Companies.</p>
                <p className="mb-5">We may change or otherwise modify this Agreement in the future in accordance with the terms and conditions herein, and you understand and agree that your continued access or use of the Services after such change signifies your acceptance of the updated or modified Agreement. We will note the date that revisions were last made to this Agreement at the bottom of this Agreement, and any revisions will take effect upon posting. We will notify registered users of our Services (such registered users to be referred to as “Account Holders”) of material changes to these terms and conditions by either sending a notice to the email address associated with the Account Holder’s profile or by placing a notice on our websites. Be sure to return to this page periodically to review the most current version of this Agreement.</p>
            </div>
        </div>
    );
};

export default Privacy;